/// @description splash
alpap = 0
fixedalpap = 1
persen = 100
logopersen = 100
logopersen = random_range(0,100);								 
randomer = true
timerngurang = false
timer = 0
ready = false
rising = true
alpa = layer_background_alpha(layer_background_get_id("Background"),alpap)
foronly = "Game ini hanyalah playtest 'The Indigo Project'"
by = "Dan dibuat oleh Lauda Dhia Raka"
disclaimer = "Peringatan!\n game ini mengandung kilatan cahaya yang tidak dianjurkan untuk para penderita penderita epilepsi"
egg[0] = "HAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH"
egg[1] = "Aku ada disini"
egg[2] = "UOOOOOOHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH"
egg[3] = "Peringatan!\n game ini mengandung kilatan cahaya yang tidak dianjurkan untuk para penderita penderita epilepsi?"
egg[4] = "ᴉsdǝlᴉdǝ ɐʇᴉɹǝpuǝd ɐʇᴉɹǝpuǝd ɐɹɐd ʞnʇun uɐʞɹnɾuɐᴉp ʞɐpᴉʇ ƃuɐʎ ɐʎɐɥɐɔ uɐʇɐlᴉʞ ƃunpuɐƃuǝɯ ᴉuᴉ ǝɯɐƃ \n ¡uɐʇɐƃuᴉɹǝԀ"
egg[5] = "Sirius is kinda bad tho"
egg[6] = "Null"
egg[7] = "Nirwana Pancarona"
egg[8] = "!natagnireP \n ispelipe atirednep atirednep arap kutnu nakrujnaid kadit gnay ayahac natalik gnudnagnem ini emag"
egg[9] = ";)"

//abis firstbeaten
ada1[0] = "Peringatan!\n Aku ada disini ;)"
//abis deathcount
if o_stats.deathcount > 10{
ada[0] = "HAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH\nHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAHHAHAHAHAHHHAHAHHAHAHAHAHAH"
ada[1] = "APAKAH KAU MELIHATKU SEKARANG?"
ada[2] = "FAKTOR ERUDERA, ADA DITANGANKU"
ada[3] = "KAU MASIH INGIN MENCOBA MELAWANKU?"
ada[4] = "MENYEDIHKAN"
ada[5] = "KAU SANGAT KERAS KEPALA, KAU TAHU ITU?"
ada[6] = "KAU TIDAK AKAN BISA MENANG MELAWANKU"
ada[7] = "BAHKAN [SANG A] TIDAK BISA MENGHENTIKANKU"
ada[8] = "PENCIPTA [SANG A], KAU MEMBERIKAN [FAKTOR ERUDERA] KE ORANG INI?"
ada[9] = "AKU BISA BERADA DISINI SELAMANYA, BERSAMAMU"
ada[10] = "KAU TIDAK TAHU KATA MENYERAH, KAU TAHU ITU?"
ada[11] = "PERCUMA"
ada[12] = "APAKAH KAU BENAR-BENAR BERPIKIR BISA MENANG?"
ada[13] = "ENYAHLAH"
}else{
ada[0] = "Menyedihkan"
ada[1] = "Percuma"
ada[2] = "Kau sangat keras kepala, kau tahu itu?"
ada[3] = "Payah"
ada[4] = "Teruslah berusaha"
ada[5] = ";)"
ada[6] = "Membosankan"
ada[7] = "Sampai kapan kau ingin disini?"
ada[8] = "Peringatan! \n Kau tidak akan menang"
ada[9] = "Pergilah"
ada[10] = "Apakah kau benar-benar berpikir bisa menang?"
ada[11] = "Haha"
ada[12] = "Menarik sekali"
ada[13] = "Kau telah meninggalkan Isagel"
}
//abis kabur
if o_stats.deathcount > 10{
run[0] = "MENGAPA KAU KABUR"
run[1] = "LEMAH"
run[2] = "KAU ADALAH PECUNDANG"
run[3] = "KEMBALI KESINI"
}else{
	run[0] = "Aku tahu kau kabur"
	run[1] = "Pecundang"
	run[2] = "Mengapa kau kabur"
	run[3] = "Aku akan selalu disini"
}
//rute damai
peace[0] = "Aku Ada disini"
peace[1] = "Tolong kembali kesini"
peace[2] = "Aku merindukanmu"
peace[3] = "Aku akan terus disini"
peace[4] = "Peringatan!\n game ini mengandung kilatan cahaya yang tidak dianjurkan untuk para penderita penderita epilepsi?"
peace[5] = "[Sayap 12: Ada Cherubim - Penguasa Aturan Imajinasi dan Seni] \n Aku Ada disini"
peace[6] = "Dimanakah kau"
peace[7] = "Tetaplah disini sampai aku tahu bagaimana mengoperasikan [Faktor Erudera]"
peace[8] = "Kau boleh keluar, tetapi tolong kembali kepadaku"
peace[9] = "Aku tetap akan berada disini untuk beberapa hari"
peace[10] = "VGVyaW1hIGthc2loIHN1ZGFoIG1lbWJhbnR1a3U="
peace[11] = "QWt1IEFkYSBkaXNpbmk="
peace[12] = ":)" 
//rute traitor
betray[0] = "PENGKHIANAT"

afterada = "NULL"

ngurang = false
setop = false
forwhat = true
disukureima = false
alpop = 0
alpip = 0;
ngurangg = false
